# -----------------------------------------------------------------------------
# Global Hydra configuration â€“ accessible to *all* modules/CLI scripts.
# -----------------------------------------------------------------------------

defaults:
  - runs@run: comparative-1-resnet18-cifarfs

results_dir: ./outputs
mode: full  # full | trial

# -----------------------------------------------------------------------------
wandb:
  entity: gengaru617-personal
  project: 2026-01-15
  mode: online
